# The default adapter in development is "async", but it only works
# within the same process. So it doesn't work for manually triggering
# cable updates from a Rails console and seeing results in the browser,
# which we do in this course. So that's why we use the "redis" adapter
# in development.

development:
  adapter: redis
  url: redis://redis:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: fishing_production
